use std::fmt;

#[derive(PartialEq, Clone, Copy, Debug)]
#[repr(u16)]
pub enum StatusCode {
	Continue = 100,
	SwitchingProtocols = 101,
	EarlyHints = 103,
	OK = 200,
	Created = 201,
	Accepted = 202,
	NonAuthoritativeInfo = 203,
	NoContent = 204,
	ResetContent = 205,
	PartialContent = 206,
	AlreadyReported = 208,
	IMUsed = 226,
	MultipleChoices = 300,
	MovedPermanently = 301,
	Found = 302,
	SeeOther = 303,
	NotModified = 304,
	UseProxy = 305,
	TemporaryRedirect = 307,
	PermanentRedirect = 308,
	BadRequest = 400,
	Unauthorized = 401,
	PaymentRequired = 402,
	Forbidden = 403,
	NotFound = 404,
	MethodNotAllowed = 405,
	NotAcceptable = 406,
	ProxyAuthRequired = 407,
	RequestTimeout = 408,
	Conflict = 409,
	Gone = 410,
	LengthRequired = 411,
	PreconditionFailed = 412,
	PayloadTooLarge = 413,
	URITooLong = 414,
	UnsupportedMediaType = 415,
	RangeNotSatisfiable = 416,
	ExpectationFailed = 417,
	ImATeapot = 418,
	MisdirectedRequest = 421,
	UnprocessableEntity = 422,
	Locked = 423,
	FailedDependency = 424,
	TooEarly = 425,
	UpgradeRequired = 426,
	PreconditionRequired = 428,
	TooManyRequests = 429,
	RequestHeaderFieldsTooLarge = 431,
	UnavailableForLegalReasons = 451,
	InternalServerError = 500,
	NotImplemented = 501,
	BadGateway = 502,
	ServiceUnavailable = 503,
	GatewayTimeout = 504,
	HTTPVersionNotSupported = 505,
	VariantAlsoNegotiates = 506,
	InsufficientStorage = 507,
	LoopDetected = 508,
	NotExtended = 510,
	NetworkAuthenticationRequired = 511,
}

impl fmt::Display for StatusCode {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		match self {
			StatusCode::Continue => write!(f, "HTTP/1.1 100 Continue"),
			StatusCode::SwitchingProtocols => write!(f, "HTTP/1.1 101 Switching Protocols"),
			StatusCode::EarlyHints => write!(f, "HTTP/1.1 103 Early Hints"),
			StatusCode::OK => write!(f, "HTTP/1.1 200 OK"),
			StatusCode::Created => write!(f, "HTTP/1.1 201 Created"),
			StatusCode::Accepted => write!(f, "HTTP/1.1 202 Accepted"),
			StatusCode::NonAuthoritativeInfo => write!(f, "HTTP/1.1 203 Non-Authoritative Information"),
			StatusCode::NoContent => write!(f, "HTTP/1.1 204 No Content"),
			StatusCode::ResetContent => write!(f, "HTTP/1.1 205 Reset Content"),
			StatusCode::PartialContent => write!(f, "HTTP/1.1 206 Partial Content"),
			StatusCode::AlreadyReported => write!(f, "HTTP/1.1 208 Already Reported"),
			StatusCode::IMUsed => write!(f, "HTTP/1.1 226 IM Used"),
			StatusCode::MultipleChoices => write!(f, "HTTP/1.1 300 Multiple Choices"),
			StatusCode::MovedPermanently => write!(f, "HTTP/1.1 301 Moved Permanently"),
			StatusCode::Found => write!(f, "HTTP/1.1 302 Found"),
			StatusCode::SeeOther => write!(f, "HTTP/1.1 303 See Other"),
			StatusCode::NotModified => write!(f, "HTTP/1.1 304 Not Modified"),
			StatusCode::UseProxy => write!(f, "HTTP/1.1 305 Use Proxy"),
			StatusCode::TemporaryRedirect => write!(f, "HTTP/1.1 307 Temporary Redirect"),
			StatusCode::PermanentRedirect => write!(f, "HTTP/1.1 308 Permanent Redirect"),
			StatusCode::BadRequest => write!(f, "HTTP/1.1 400 Bad Request"),
			StatusCode::Unauthorized => write!(f, "HTTP/1.1 401 Unauthorized"),
			StatusCode::PaymentRequired => write!(f, "HTTP/1.1 402 Payment Required"),
			StatusCode::Forbidden => write!(f, "HTTP/1.1 403 Forbidden"),
			StatusCode::NotFound => write!(f, "HTTP/1.1 404 Not Found"),
			StatusCode::MethodNotAllowed => write!(f, "HTTP/1.1 405 Method Not Allowed"),
			StatusCode::NotAcceptable => write!(f, "HTTP/1.1 406 Not Acceptable"),
			StatusCode::ProxyAuthRequired => write!(f, "HTTP/1.1 407 Proxy Authentication Required"),
			StatusCode::RequestTimeout => write!(f, "HTTP/1.1 408 Request Timeout"),
			StatusCode::Conflict => write!(f, "HTTP/1.1 409 Conflict"),
			StatusCode::Gone => write!(f, "HTTP/1.1 410 Gone"),
			StatusCode::LengthRequired => write!(f, "HTTP/1.1 411 Length Required"),
			StatusCode::PreconditionFailed => write!(f, "HTTP/1.1 412 Precondition Failed"),
			StatusCode::PayloadTooLarge => write!(f, "HTTP/1.1 413 Payload Too Large"),
			StatusCode::URITooLong => write!(f, "HTTP/1.1 414 URI Too Long"),
			StatusCode::UnsupportedMediaType => write!(f, "HTTP/1.1 415 Unsupported Media Type"),
			StatusCode::RangeNotSatisfiable => write!(f, "HTTP/1.1 416 Range Not Satisfiable"),
			StatusCode::ExpectationFailed => write!(f, "HTTP/1.1 417 Expectation Failed"),
			StatusCode::ImATeapot => write!(f, "HTTP/1.1 418 I'm a teapot"),
			StatusCode::MisdirectedRequest => write!(f, "HTTP/1.1 421 Misdirected Request"),
			StatusCode::UnprocessableEntity => write!(f, "HTTP/1.1 422 Unprocessable Entity"),
			StatusCode::Locked => write!(f, "HTTP/1.1 423 Locked"),
			StatusCode::FailedDependency => write!(f, "HTTP/1.1 424 Failed Dependency"),
			StatusCode::TooEarly => write!(f, "HTTP/1.1 425 Too Early"),
			StatusCode::UpgradeRequired => write!(f, "HTTP/1.1 426 Upgrade Required"),
			StatusCode::PreconditionRequired => write!(f, "HTTP/1.1 428 Precondition Required"),
			StatusCode::TooManyRequests => write!(f, "HTTP/1.1 429 Too Many Requests"),
			StatusCode::RequestHeaderFieldsTooLarge => {
				write!(f, "HTTP/1.1 431 Request Header Fields Too Large")
			}
			StatusCode::UnavailableForLegalReasons => {
				write!(f, "HTTP/1.1 451 Unavailable For Legal Reasons")
			}
			StatusCode::InternalServerError => write!(f, "HTTP/1.1 500 Internal Server Error"),
			StatusCode::NotImplemented => write!(f, "HTTP/1.1 501 Not Implemented"),
			StatusCode::BadGateway => write!(f, "HTTP/1.1 502 Bad Gateway"),
			StatusCode::ServiceUnavailable => write!(f, "HTTP/1.1 503 Service Unavailable"),
			StatusCode::GatewayTimeout => write!(f, "HTTP/1.1 504 Gateway Timeout"),
			StatusCode::HTTPVersionNotSupported => write!(f, "HTTP/1.1 505 HTTP Version Not Supported"),
			StatusCode::VariantAlsoNegotiates => write!(f, "HTTP/1.1 506 Variant Also Negotiates"),
			StatusCode::InsufficientStorage => write!(f, "HTTP/1.1 507 Insufficient Storage"),
			StatusCode::LoopDetected => write!(f, "HTTP/1.1 508 Loop Detected"),
			StatusCode::NotExtended => write!(f, "HTTP/1.1 510 Not Extended"),
			StatusCode::NetworkAuthenticationRequired => {
				write!(f, "HTTP/1.1 511 Network Authentication Required")
			}
		}
	}
}
